name: "dbt_project"
version: "0.1.0"
require-dbt-version: ">=1.9.0"

profile: "dbt_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
